services:
  frontend:
    image: yong1le/quirknotes_frontend
    ports:
    - "3000:3000"
    depends_on:
    - backend

  backend:
    image: yong1le/quirknotes_backend 
    ports:
    - "4000:4000"
    environment:
    - ENV=Docker
    depends_on:
    - mongodb

  mongodb:
    image: mongo:latest
    ports:
    - "27017:27017"
